

services:
  web:
    build: ./web_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - ml-client
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - ML_CLIENT_HOST=http://ml-client:6000
    volumes:
      - ./web_app:/app
    networks:
      - app-network

  ml-client:
    build: ./machine_learning_client
    ports:
      - "6000:6000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - ./machine_learning_client:/app
      - ml-model-data:/app/pretrained_models
    networks:
      - app-network

  mongodb:
    image: mongo:6.0 
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  ml-model-data:

networks:
  app-network:
