name: ML Client CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  client-test:
    name: Test Client Subsystem
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pymongo requests torchaudio torch numpy speechbrain
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -v --cov=machine-learning-client machine-learning-client/tests/test_ml_client.py
