name: Web App CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URI: mongodb://localhost:27017/
      ML_CLIENT_HOST: http://localhost:6000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pymongo requests==2.31.0 python-dotenv pytest


      - name: Lint with pylint
        run: |
          pylint web-app/app.py

      - name: Format check with black
        run: |
          black --check web-app/

      - name: Run tests and check coverage
        working-directory: web_app
        run: |
          pytest --cov=app /tests/test_webapp.py
